### ISSUE TITLE
New release of opam-0install

### ISSUE THREAD

**Issue by NathanReb** [ocaml-opam/opam-0install-solver#41]
opam-monorepo depends on features that have not been released yet and therefore needs to pin opam-0install.

It is not highly critical as opam-monorepo does uses itself to pack all its dependencies in the release tarball.

Getting rid of the pin-depends for opam-0install would prove useful as it becomes easy to forget about it after a while. I was preparing the next release of opam-monorepo and just re-discovered we were relying on a dev version of opam-0install.

Please let me know if I can be of any help here!

**Comment by talex5** [comment]
I see @kit-ty-kate has a couple of active PRs at the moment. Should we wait for those to be merged first?

**Comment by kit-ty-kate** [comment]
No, no need to wait for me.

**Comment by NathanReb** [comment]
As I mentioned above, there's no particular rush on our side so feel free to merge those before cutting a release if that makes things simpler for you.

I subscribed to the releases on the repo and I'll get notified when this issue is closed as a reminder to remove the pin-depends on our side and that's pretty much all I need!
