### ISSUE TITLE
Split opam-0install and opam-0install-cudf

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-opam/opam-0install-solver#54]
opam-0install and opam-0install-cudf are both separated project and do not interact with each other.
Adding opam-0install-cudf to this repository (https://github.com/ocaml-opam/opam-0install-solver/pull/11) made sense at the time because the codebase was a copy/replace from opam-0install and i wanted to keep the changes in sync.

Nowadays, while the code hasn't change that much, i feel like they're both different enough, and can even impede each other (e.g. there is no CI because of https://github.com/ocurrent/ocaml-ci/issues/257).

Thus i propose to split this repository into two:
- opam-0install would move to the [ocurrent](https://github.com/ocurrent) org (i feel that it makes sense, but feel free to propose something else)
- opam-0install-cudf would move to ocaml-opam/opam-0install-cudf

@talex5 what do you think?

**Comment by talex5** [comment]
Splitting seems fine, but I don't see why this one needs to move. It uses opam-format package metadata from opam-repository and is used in other opam-related tools (e.g. opam2nix), but it has nothing in particular to do with OCurrent, so I think it's better to keep it here.

**Comment by kit-ty-kate** [comment]
> It uses opam-format package metadata from opam-repository and is used in other opam-related tools (e.g. opam2nix), but it has nothing in particular to do with OCurrent, so I think it's better to keep it here.

fair enough, my reasoning came from the fact i thought opam-0install was mostly only used for ocaml-ci, i didn't know about other users such as opam2nix.

I'll open a PR and set that up soon
